### ISSUE TITLE
Free Fire Crash when injected frida

### ISSUE THREAD

**Issue by inderxkang** [springmusk026/Frida-Il2cpp-Dumper#1]
![Screenshot (29)](https://github.com/user-attachments/assets/fb24496d-fd24-4a45-b561-a6bdc6981cc9)
C:\Users\Administrator\Frida-Il2cpp-Dumper>npm run spawn

> il2cpp@1.0.0 spawn
> frida -U -f com.dts.freefireth -l dist/agent.js

     ____
    / _  |   Frida 16.5.6 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to SM A730F (id=3300d236dd0f145d)
Spawned `com.dts.freefireth`. Resuming main thread!
[SM A730F::com.dts.freefireth ]-> Process crashed: java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000d6e

***
FATAL EXCEPTION: main
Process: com.dts.freefireth, PID: 2671
java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000d6e
Build fingerprint: 'samsung/jackpot2ltexx/jackpot2lte:9/PPR1.180610.011/A730FXXS7CUL2:user/release-keys'
Revision: '0'
pid: 2671, tid: 2707, name: Thread-12  >>> com.dts.freefireth <<<
    r0 00000d6f  r1 3e54c000  r2 00000fff  r3 1366630c
    r4 0000000a  r5 c37d0930  r6 00000012  r7 00000d6f
    r8 bf85549c  r9 00000014  sl 00000001  fp 00000d6f
    ip 0000deec  sp c2e63890  lr 00000d6f  pc 00000d6e  cpsr e9754d10

        at Unknown.00000d6e(Unknown Source:0)
        at Unknown.00000d6d(Unknown Source:0)
***
[SM A730F::com.dts.freefireth ]->

Thank you for using Frida!

**Comment by springmusk026** [comment]
It looks like the crash is happening because the game is detecting Frida and triggering a crash. This is a common issue with anti-cheat mechanisms in many games that actively look for dynamic instrumentation tools like Frida. To resolve this, you will need to implement detection prevention methods.

**Comment by inderxkang** [comment]
Oh I have subscribed LGL Team on telegram there is free fire 1.107 dump.cs can you update it or just suggest a method you use so I can do it myself

**Comment by inderxkang** [comment]
I know I'm going to ask foolish thing 
But is it somehow possible to extract c# scripts or dummy dlls 
I just want the UMAMeshAsset.cs
